/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_blokaly_ceres_system_Clock */

#ifndef _Included_com_blokaly_ceres_system_Clock
#define _Included_com_blokaly_ceres_system_Clock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_blokaly_ceres_system_Clock
 * Method:    currentTimeInNanos
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_blokaly_ceres_system_Clock_currentTimeInNanos
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
